---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kedger-controller
  namespace: default
  labels:
    api: kedger
    controller: "true"
spec:
  selector:
    matchLabels:
      api: kedger
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: kedger
        controller: "true"
    spec:
      containers:
      - name: controller
        image: pdettori/kedger
        command:
        - "./controller-manager"
        args:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: kedger
